# Generated by Django 4.1.1 on 2022-11-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='phone',
        ),
    ]
