# Generated by Django 4.1.1 on 2022-11-22 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_remove_extension_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extension',
        ),
    ]
